// -- TAGS: Lenguajes y Tecnologías
export const tecnologias = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "Perl",
  "R",
  "Dart",
  "Scala",
  "Objective-C",
  "Elixir",
  "Haskell",
  "Bash",
  "Shell",
  "Lua",
  "MATLAB",
  "SQL",
  "NoSQL",
  "GraphQL",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Firebase",
  "Supabase",
  "Redis",
  "React",
  "Vue",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Gatsby",
  "Remix",
  "React Native",
  "Expo",
  "Ionic",
  "Flutter",
  "Electron",
  "Tailwind CSS",
  "Bootstrap",
  "SASS",
  "LESS",
  "Styled Components",
  "Chakra UI",
  "Material UI",
  "Vite",
  "Webpack",
  "Parcel",
  "Rollup",
  "ESLint",
  "Prettier",
  "Babel",
  "Jest",
  "Vitest",
  "Mocha",
  "Cypress",
  "Playwright",
  "Testing Library",
  "Storybook",
  "Redux",
  "Zustand",
  "Jotai",
  "MobX",
  "Recoil",
  "Express.js",
  "Fastify",
  "NestJS",
  "Hapi.js",
  "Koa.js",
  "Node.js",
  "Deno",
  "Spring Boot",
  "Laravel",
  "Symfony",
  "Django",
  "Flask",
  "Ruby on Rails",
  "ASP.NET",
  "Strapi",
  "Sanity",
  "Contentful",
  "WordPress",
  "Shopify",
  "Docker",
  "Kubernetes",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "CI/CD",
  "Linux",
  "Nginx",
  "Vercel",
  "Netlify",
];


// colores para tecnologias
export const getColorForTech = (tech) => {
  const colors = {
    HTML: "bg-orange-500",
    CSS: "bg-blue-500",
    JavaScript: "bg-yellow-400",
    TypeScript: "bg-blue-600",
    Python: "bg-yellow-300",
    Java: "bg-red-600",
    C: "bg-gray-700",
    "C++": "bg-blue-700",
    "C#": "bg-purple-700",
    Go: "bg-cyan-600",
    Rust: "bg-orange-800",
    Kotlin: "bg-purple-500",
    Swift: "bg-orange-400",
    PHP: "bg-indigo-600",
    Ruby: "bg-red-500",
    Perl: "bg-indigo-400",
    R: "bg-blue-400",
    Dart: "bg-sky-500",
    Scala: "bg-red-600",
    "Objective-C": "bg-gray-600",
    Elixir: "bg-purple-800",
    Haskell: "bg-indigo-700",
    Bash: "bg-gray-800",
    Shell: "bg-gray-600",
    Lua: "bg-blue-300",
    MATLAB: "bg-pink-500",
    SQL: "bg-indigo-500",
    NoSQL: "bg-yellow-600",
    GraphQL: "bg-pink-400",
    MongoDB: "bg-green-600",
    MySQL: "bg-yellow-700",
    PostgreSQL: "bg-blue-700",
    SQLite: "bg-gray-500",
    Firebase: "bg-amber-400",
    Supabase: "bg-emerald-500",
    Redis: "bg-red-600",
    React: "bg-sky-400",
    Vue: "bg-green-500",
    Angular: "bg-red-700",
    Svelte: "bg-orange-600",
    "Next.js": "bg-neutral-800",
    "Nuxt.js": "bg-green-700",
    Gatsby: "bg-purple-600",
    Remix: "bg-blue-800",
    "React Native": "bg-blue-400",
    Expo: "bg-black",
    Ionic: "bg-blue-500",
    Flutter: "bg-sky-500",
    Electron: "bg-gray-700",
    "Tailwind CSS": "bg-teal-400",
    Bootstrap: "bg-purple-500",
    SASS: "bg-pink-600",
    LESS: "bg-blue-600",
    "Styled Components": "bg-purple-400",
    "Chakra UI": "bg-teal-500",
    "Material UI": "bg-blue-500",
    Vite: "bg-violet-400",
    Webpack: "bg-blue-400",
    Parcel: "bg-yellow-500",
    Rollup: "bg-red-500",
    ESLint: "bg-indigo-500",
    Prettier: "bg-pink-400",
    Babel: "bg-yellow-500",
    Jest: "bg-red-500",
    Vitest: "bg-lime-500",
    Mocha: "bg-brown-500",
    Cypress: "bg-green-500",
    Playwright: "bg-gray-600",
    "Testing Library": "bg-red-400",
    Storybook: "bg-fuchsia-500",
    Redux: "bg-purple-600",
    Zustand: "bg-orange-500",
    Jotai: "bg-green-600",
    MobX: "bg-pink-500",
    Recoil: "bg-blue-500",
    "Express.js": "bg-gray-800",
    Fastify: "bg-black",
    NestJS: "bg-red-600",
    "Hapi.js": "bg-yellow-600",
    "Koa.js": "bg-teal-600",
    "Node.js": "bg-green-700",
    Deno: "bg-black",
    "Spring Boot": "bg-green-600",
    Laravel: "bg-red-600",
    Symfony: "bg-black",
    Django: "bg-green-800",
    Flask: "bg-gray-600",
    "Ruby on Rails": "bg-red-500",
    "ASP.NET": "bg-blue-700",
    Strapi: "bg-indigo-500",
    Sanity: "bg-red-400",
    Contentful: "bg-blue-300",
    WordPress: "bg-blue-600",
    Shopify: "bg-green-500",
    Docker: "bg-blue-500",
    Kubernetes: "bg-blue-700",
    Git: "bg-orange-500",
    GitHub: "bg-gray-800",
    GitLab: "bg-orange-600",
    Bitbucket: "bg-blue-600",
    "CI/CD": "bg-cyan-600",
    Linux: "bg-gray-700",
    Nginx: "bg-green-600",
    Vercel: "bg-black",
    Netlify: "bg-emerald-500",
    default: "bg-gray-500",
  };

  return colors[tech] || colors.default;
};

